#ifndef RATINGWIDGETPLUGIN_GLOBAL_H
#define RATINGWIDGETPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RATINGWIDGETPLUGIN_LIBRARY)
#  define RATINGWIDGETPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RATINGWIDGETPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RATINGWIDGETPLUGIN_GLOBAL_H
